# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "nuclei-securecodebox-scan"
spec:
  scanType: "nuclei"
  parameters:
    # Target domain name of the finding and start a nuclei scan
    - "-u"
    - "https://www.secureCodeBox.io"
