# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "wpscan-old-wordpress-internal"
spec:
  scanType: "wpscan"
  parameters:
    - "--url"
    - old-wordpress.demo-targets.svc.cluster.local
    - "-e"
    - "vp"
    - "--plugins-detection"
    - "mixed"
