# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

version: "2" # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 300
  method-lines:
    config:
      threshold: 50
  similar-code:
    enabled: false
  identical-code:
    enabled: false
# plugins:
#   eslint:
#     enabled: true
#     channel: "eslint-7"
#   fixme:
#     enabled: true
#   golint:
#     enabled: true
#   gofmt:
#     enabled: true
#   govet:
#     enabled: true
#   markdownlint:
#     enabled: true
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/__testFiles__/"
  - "**/__snapshots__/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.deepcopy.go"
  - "**/*.test.js"
  - "**/*.test.ts"
  - "**/*.d.ts"
  # Generated 
  - "**/hooks/cascading-scans/scan-helpers.js"
  - "**/hooks/cascading-scans/hook.js"
  # Auto Generated by kubernetes java client
  - "**/hooks/persistence-defectdojo/src/main/java/io/securecodebox/models/"
