# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to view autodiscoveryconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autodiscoveryconfig-viewer-role
rules:
- apiGroups:
  - config.securecodebox.io
  resources:
  - autodiscoveryconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.securecodebox.io
  resources:
  - autodiscoveryconfigs/status
  verbs:
  - get
