# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: typo3scan-example
spec:
  scanType: "typo3scan"
  parameters:
    - "-d"
    - "https://www.typo3.example.com" # Change to the website you want to scan
    # Only show vulnerable extensions
    - "--vuln"
    # Set the number of threads to use for enumerating extensions at 10
    - "--threads"
    - "10"