# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    description: DeclarativeCombinedScansHooks needs to have the rights to create new scans and the usual patch rules to update the scan status
  name: cascading-scans
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cascading-scans
subjects:
  - kind: ServiceAccount
    name: cascading-scans
