# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    description: DeclarativeCombinedScansHooks needs to have the rights to create new scans and the usual patch rules to update the scan status
  name: cascading-scans
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - execution.securecodebox.io
    resources:
      - scans
    verbs:
      - get
      - create
  - apiGroups:
      - execution.securecodebox.io
    resources:
      - parsedefinitions
    verbs:
      - get
  - apiGroups:
      - execution.securecodebox.io
    resources:
      - scans/status
    verbs:
      - get
      - patch
  - apiGroups:
      - cascading.securecodebox.io
    resources:
      - cascadingrules
    verbs:
      - get
      - list
