# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "scan-website-with-jwt"
spec:
  scanType: "angularjs-csti-scanner"
  parameters:
    - "-d"
    - "https://example.com"
    - "-c"
    # you should always specify a max depth when crawling
    - "-md"
    - "3"
  volumes:
    - name: "acstis-config"
      configMap:
        name: "acstis-config"
  volumeMounts:
    - name: "acstis-config"
      mountPath: "/home/angularjscsti/acstis/config/"
