# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: cascading.securecodebox.io/v1
kind: CascadingRule
metadata:
  name: cascadingrule-sample
spec:
  # Add fields here
  foo: bar
