# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: execution.securecodebox.io/v1
kind: ParseDefinition
metadata:
  name: "nmap-xml"
spec:
  image: securecodebox/nmap-parser
